import { Product } from '../types/product';

// Sample Products Data
export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones',
    price: 199.99,
    image: '🎧',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life.',
    category: 'Electronics',
    rating: 4.5,
    reviews: 234,
  },
  {
    id: '2',
    name: 'Smart Watch',
    price: 299.99,
    image: '⌚',
    description: 'Track your fitness, heart rate, and sleep with this advanced smartwatch.',
    category: 'Electronics',
    rating: 4.8,
    reviews: 567,
  },
  {
    id: '3',
    name: 'Running Shoes',
    price: 129.99,
    image: '👟',
    description: 'Lightweight and comfortable running shoes for any terrain.',
    category: 'Sports',
    rating: 4.3,
    reviews: 189,
  },
  {
    id: '4',
    name: 'Yoga Mat',
    price: 49.99,
    image: '🧘',
    description: 'Non-slip yoga mat with extra cushioning for comfort.',
    category: 'Sports',
    rating: 4.6,
    reviews: 445,
  },
  {
    id: '5',
    name: 'Coffee Maker',
    price: 79.99,
    image: '☕',
    description: 'Programmable coffee maker with thermal carafe.',
    category: 'Home',
    rating: 4.4,
    reviews: 312,
  },
  {
    id: '6',
    name: 'Backpack',
    price: 89.99,
    image: '🎒',
    description: 'Water-resistant backpack with laptop compartment.',
    category: 'Accessories',
    rating: 4.7,
    reviews: 678,
  },
  {
    id: '7',
    name: 'Sunglasses',
    price: 159.99,
    image: '🕶️',
    description: 'Polarized sunglasses with UV protection.',
    category: 'Accessories',
    rating: 4.2,
    reviews: 156,
  },
  {
    id: '8',
    name: 'Plant Pot',
    price: 24.99,
    image: '🪴',
    description: 'Modern ceramic plant pot with drainage hole.',
    category: 'Home',
    rating: 4.5,
    reviews: 89,
  },
];

export const CATEGORIES = ['All', 'Electronics', 'Sports', 'Home', 'Accessories'];
